// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFTrs5qcWhkINdhzl87VfamJsZTmawS4',
    appId: '1:318747677620:web:deb92bf6fb5177d0ea58e1',
    messagingSenderId: '318747677620',
    projectId: 'my-app-692f2',
    authDomain: 'my-app-692f2.firebaseapp.com',
    storageBucket: 'my-app-692f2.appspot.com',
    measurementId: 'G-SM2ZWBQX7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCokbqkbgR4SMVnuFk5TD5OP7g6FAKvsZU',
    appId: '1:318747677620:android:5f803cfab274e73fea58e1',
    messagingSenderId: '318747677620',
    projectId: 'my-app-692f2',
    storageBucket: 'my-app-692f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPNZT_uGWLV9f4b_FeEjDEGPOxhMe7qlE',
    appId: '1:318747677620:ios:ae6fb510d8e8a982ea58e1',
    messagingSenderId: '318747677620',
    projectId: 'my-app-692f2',
    storageBucket: 'my-app-692f2.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPNZT_uGWLV9f4b_FeEjDEGPOxhMe7qlE',
    appId: '1:318747677620:ios:ae6fb510d8e8a982ea58e1',
    messagingSenderId: '318747677620',
    projectId: 'my-app-692f2',
    storageBucket: 'my-app-692f2.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATFTrs5qcWhkINdhzl87VfamJsZTmawS4',
    appId: '1:318747677620:web:852b13cfbab32858ea58e1',
    messagingSenderId: '318747677620',
    projectId: 'my-app-692f2',
    authDomain: 'my-app-692f2.firebaseapp.com',
    storageBucket: 'my-app-692f2.appspot.com',
    measurementId: 'G-824BLQEGHN',
  );

}